#line 1 "Lexer.C"

#line 3 "Lexer.C"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define Stella_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer Stella_create_buffer
#endif

#ifdef yy_delete_buffer
#define Stella_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer Stella_delete_buffer
#endif

#ifdef yy_scan_buffer
#define Stella_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer Stella_scan_buffer
#endif

#ifdef yy_scan_string
#define Stella_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string Stella_scan_string
#endif

#ifdef yy_scan_bytes
#define Stella_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes Stella_scan_bytes
#endif

#ifdef yy_init_buffer
#define Stella_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer Stella_init_buffer
#endif

#ifdef yy_flush_buffer
#define Stella_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer Stella_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define Stella_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state Stella_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define Stella_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer Stella_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define Stellapush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state Stellapush_buffer_state
#endif

#ifdef yypop_buffer_state
#define Stellapop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state Stellapop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define Stellaensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack Stellaensure_buffer_stack
#endif

#ifdef yylex
#define Stellalex_ALREADY_DEFINED
#else
#define yylex Stellalex
#endif

#ifdef yyrestart
#define Stellarestart_ALREADY_DEFINED
#else
#define yyrestart Stellarestart
#endif

#ifdef yylex_init
#define Stellalex_init_ALREADY_DEFINED
#else
#define yylex_init Stellalex_init
#endif

#ifdef yylex_init_extra
#define Stellalex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra Stellalex_init_extra
#endif

#ifdef yylex_destroy
#define Stellalex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy Stellalex_destroy
#endif

#ifdef yyget_debug
#define Stellaget_debug_ALREADY_DEFINED
#else
#define yyget_debug Stellaget_debug
#endif

#ifdef yyset_debug
#define Stellaset_debug_ALREADY_DEFINED
#else
#define yyset_debug Stellaset_debug
#endif

#ifdef yyget_extra
#define Stellaget_extra_ALREADY_DEFINED
#else
#define yyget_extra Stellaget_extra
#endif

#ifdef yyset_extra
#define Stellaset_extra_ALREADY_DEFINED
#else
#define yyset_extra Stellaset_extra
#endif

#ifdef yyget_in
#define Stellaget_in_ALREADY_DEFINED
#else
#define yyget_in Stellaget_in
#endif

#ifdef yyset_in
#define Stellaset_in_ALREADY_DEFINED
#else
#define yyset_in Stellaset_in
#endif

#ifdef yyget_out
#define Stellaget_out_ALREADY_DEFINED
#else
#define yyget_out Stellaget_out
#endif

#ifdef yyset_out
#define Stellaset_out_ALREADY_DEFINED
#else
#define yyset_out Stellaset_out
#endif

#ifdef yyget_leng
#define Stellaget_leng_ALREADY_DEFINED
#else
#define yyget_leng Stellaget_leng
#endif

#ifdef yyget_text
#define Stellaget_text_ALREADY_DEFINED
#else
#define yyget_text Stellaget_text
#endif

#ifdef yyget_lineno
#define Stellaget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno Stellaget_lineno
#endif

#ifdef yyset_lineno
#define Stellaset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno Stellaset_lineno
#endif

#ifdef yyget_column
#define Stellaget_column_ALREADY_DEFINED
#else
#define yyget_column Stellaget_column
#endif

#ifdef yyset_column
#define Stellaset_column_ALREADY_DEFINED
#else
#define yyset_column Stellaset_column
#endif

#ifdef yywrap
#define Stellawrap_ALREADY_DEFINED
#else
#define yywrap Stellawrap
#endif

#ifdef yyget_lval
#define Stellaget_lval_ALREADY_DEFINED
#else
#define yyget_lval Stellaget_lval
#endif

#ifdef yyset_lval
#define Stellaset_lval_ALREADY_DEFINED
#else
#define yyset_lval Stellaset_lval
#endif

#ifdef yyget_lloc
#define Stellaget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc Stellaget_lloc
#endif

#ifdef yyset_lloc
#define Stellaset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc Stellaset_lloc
#endif

#ifdef yyalloc
#define Stellaalloc_ALREADY_DEFINED
#else
#define yyalloc Stellaalloc
#endif

#ifdef yyrealloc
#define Stellarealloc_ALREADY_DEFINED
#else
#define yyrealloc Stellarealloc
#endif

#ifdef yyfree
#define Stellafree_ALREADY_DEFINED
#else
#define yyfree Stellafree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define Stellawrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[259] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   93,   91,   90,   90,   91,   91,
       35,    3,    4,   25,   23,    1,   24,   27,   26,   89,
       10,    2,   17,    9,   19,   86,   86,   86,   86,   86,
       86,    7,    8,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
        5,   13,    6,   91,   92,   84,   85,   84,   22,   87,
       87,   11,   82,   81,   89,   16,    0,   18,   14,   21,
       12,   20,   86,   86,   86,   86,   86,   86,   86,   86,
       42,   86,   86,   86,   86,   86,   86,   52,   86,   86,

       56,   57,   86,   86,   86,   86,   86,   67,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   15,   80,   83,
       81,    0,   86,   37,   86,   38,   39,   86,   41,   86,
       86,   86,   86,   86,   86,   86,   86,   51,   86,   86,
       86,   58,   60,   86,   62,   86,   65,   66,   86,   86,
       86,   86,   86,   86,   74,   86,   86,   86,   86,   86,
        0,   36,   86,   86,   40,   43,   86,   45,   46,   47,
       86,   86,   86,   53,   86,   86,   86,   86,   86,   86,
       86,   86,   69,   70,   86,   73,   75,   86,   77,   86,
       79,   88,   86,   86,   44,   86,   86,   50,   86,   86,

       86,   86,   86,   64,   86,   86,   71,   86,   86,   86,
       86,   86,   86,   86,   49,   54,   86,   59,   86,   63,
       31,   68,   72,   76,   86,   86,   86,   86,   86,   86,
       86,   86,   55,   86,   78,   86,   86,   86,   86,   86,
       34,   86,   61,   86,   86,   86,   86,   32,   48,   28,
       86,   30,   86,   86,   33,   86,   29,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,    1,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   31,   29,   29,
       29,   29,   29,   32,   33,   29,   29,   29,   29,   29,
       34,    1,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   29,   46,   47,   48,
       49,   50,   29,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       63,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   64,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    4,    4,    3,    1,    1,    1,
        1,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[264] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   62,   63,  136, 1331, 1331, 1331,  113,   55,
     1331, 1331, 1331, 1331, 1331, 1331,  111, 1331,   59,   54,
      111, 1331,   59,   55,  110,   73,   76,   77,   80,  102,
      106, 1331, 1331,  117,  123,  140,  144,   59,  126,  142,
      151,  157,  164,  171,  173,  180,  187,  202,  204,  209,
     1331,   94, 1331,   42, 1331, 1331, 1331,   89, 1331,   75,
      114, 1331, 1331,    0,   67, 1331,   44, 1331, 1331, 1331,
     1331, 1331,  211,  218,  224,  231,  233,  247,  253,  263,
      268,  270,  283,  288,  290,  304,  309,  311,  324,  331,

      337,  344,  351,  357,  364,  366,  371,  381,  386,  388,
      401,  406,  411,  425,  434,  440,  447, 1331, 1331, 1331,
        0,  486,  470,  449,  484,  503,  493,  508,  498,  517,
      530,  535,  540,  545,  554,  559,  561,  574,  580,  587,
      589,  594,  596,  603,  610,  617,  623,  630,  632,  637,
      650,  655,  657,  670,  664,  679,  677,  684,  686,  699,
       65,  693,  722,  728,  709,  715,  735,  737,  744,  750,
      757,  763,  772,  777,  782,  787,  792,  797,  807,  813,
      826,  831,  836,  841,  846,  851,  856,  861,  866,  871,
      876, 1331,  895,  885,  900,  902,  916,  909,  922,  929,

      935,  942,  949,  944,  958,  963,  965,  978,  983,  985,
      998, 1000, 1015, 1017, 1022, 1024, 1037, 1042, 1051, 1044,
     1058, 1060, 1065, 1067, 1074, 1080, 1087, 1089, 1096, 1105,
     1112, 1119, 1121, 1134, 1128, 1141, 1143, 1148, 1157, 1163,
     1170, 1172, 1177, 1187, 1192, 1197, 1207, 1212, 1214, 1227,
     1229, 1236, 1243, 1245, 1252, 1258, 1265, 1331, 1316, 1320,
       74, 1322, 1326
    } ;

static const flex_int16_t yy_def[264] =
    {   0,
      258,    1,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  260,  260,  258,  258,  258,  258,  258,  261,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  262,  262,  262,  262,  262,
      262,  258,  258,  262,  262,  262,  262,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  261,
      261,  258,  258,  263,  258,  258,  258,  258,  258,  258,
      258,  258,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,  258,  258,  258,
      263,  258,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
      122,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,  258,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,    0,  258,  258,
      258,  258,  258
    } ;

static const flex_int16_t yy_nxt[1396] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   31,   32,   33,   34,
       35,   16,   36,   37,   36,   36,   36,   36,   36,   38,
       39,   40,   41,   42,   43,   36,   44,   36,   45,   36,
       46,   47,   48,   36,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   36,   36,   36,   61,
       62,   63,   16,   64,   67,   67,   70,   73,   75,   75,
       68,   68,   74,   77,   80,   81,   83,   71,   78,   83,
       83,   75,   75,   83,   83,  192,   70,   83,   83,   83,
       70,   83,   83,   83,   83,   84,   83,   83,   83,  100,

      122,   83,  120,   84,  119,   83,   84,   84,   83,   83,
       70,   83,   83,   83,  118,   83,   87,   83,   83,   79,
       83,   86,   83,   83,   85,   70,   83,   83,   83,   82,
       76,   72,   69,   83,   83,  258,  258,   83,   83,   83,
      258,   83,  258,   83,   83,  258,  258,   83,  258,   70,
       88,   83,   83,   89,  258,   83,   83,  258,   83,   92,
       83,   83,   84,  258,   90,   83,  258,  101,   91,  258,
       84,   93,  258,  102,   84,   83,  258,  258,  103,   83,
       96,  258,  104,  258,  258,   94,   84,  105,   97,   84,
       84,   98,   99,   84,  258,   84,   95,  106,   84,   84,

       84,   84,  258,  258,   84,  107,  258,  109,   84,   84,
      258,   84,   84,  110,  108,   84,   84,   84,   84,   84,
       84,   84,  258,   84,   84,  258,  258,   84,   84,  258,
      112,   84,  258,  111,   84,   84,  258,  113,   84,  258,
      116,  258,  258,  258,  114,   84,   84,   84,   84,  115,
       84,   84,   84,  117,   84,   84,   84,   84,   84,   84,
       84,  258,   84,  258,  258,   84,   84,   84,   84,   84,
      258,   84,  123,  258,  258,   84,  124,   84,   84,   84,
       84,   84,  125,   84,  258,  126,  258,  258,  258,   84,
      258,   84,  258,  258,   84,   84,  127,  128,  258,   84,

       84,   84,  129,  258,   84,  258,   84,   84,  258,  258,
       84,   84,   84,  258,   84,   84,   84,   84,   84,   84,
      258,  130,  131,  258,   84,  258,   84,   84,  135,  258,
      132,   84,   84,  133,   84,   84,   84,   84,   84,  134,
       84,  258,  136,  258,  258,   84,  258,   84,   84,  137,
      258,   84,   84,   84,  258,   84,   84,   84,   84,   84,
       84,  258,  258,  258,  258,  138,  258,   84,   84,  139,
      258,   84,   84,   84,  140,   84,  258,  258,  141,   84,
       84,   84,  258,  258,   84,   84,  258,   84,   84,  142,
      258,   84,   84,   84,  143,   84,  258,  258,  144,   84,

       84,   84,   84,  258,   84,   84,  258,   84,   84,  145,
       84,   84,   84,   84,   84,   84,  146,   84,   84,   84,
      258,  147,   84,  148,   84,   84,  258,  258,   84,   84,
       84,  258,   84,  149,   84,   84,   84,   84,  258,  151,
      150,  258,   84,  258,  258,   84,  152,   84,   84,   84,
       84,  258,  258,   84,   84,   84,  153,  258,   84,   84,
      258,   84,  258,  258,  154,  258,  258,  258,  155,   84,
       84,  258,   84,   84,  156,  157,   84,  258,  158,  258,
      258,   84,   84,   84,   84,   84,  258,   84,   84,  258,
      159,   84,  258,   84,   84,   84,   84,   84,  258,  160,

      161,  161,  258,  258,  258,  258,   84,  258,  161,  161,
      161,  161,  161,  161,   84,  162,  258,   84,   84,  164,
       84,  258,  161,  161,  161,  161,  161,  161,   84,   84,
      258,   84,   84,  258,   84,  258,  163,   84,  258,   84,
       84,   84,   84,  258,   84,   84,   84,   84,  258,  258,
       84,   84,   84,   84,  258,   84,   84,  258,  258,  258,
      165,   84,  258,  258,   84,   84,   84,  258,  167,  166,
      258,   84,  258,  258,   84,  258,   84,   84,   84,   84,
      169,   84,   84,   84,   84,  170,  168,   84,   84,   84,
       84,  258,   84,   84,  171,   84,  258,   84,   84,  172,

      258,   84,   84,   84,  258,   84,   84,   84,   84,   84,
       84,  258,  173,  258,  258,  258,   84,  258,   84,  174,
      258,   84,   84,  175,   84,   84,  258,   84,   84,  176,
       84,   84,   84,   84,   84,   84,   84,   84,  177,   84,
       84,   84,   84,   84,   84,  178,   84,   84,  258,  258,
       84,   84,  258,   84,   84,  180,  258,   84,   84,   84,
      179,   84,  258,  258,   84,   84,   84,   84,   84,  258,
       84,   84,  258,   84,   84,  258,  181,   84,   84,   84,
       84,   84,  258,  258,   84,   84,   84,  258,  183,  258,
      182,   84,  258,   84,   84,  258,  258,   84,   84,   84,

       84,   84,  184,   84,   84,  185,   84,  258,   84,  258,
      186,   84,   84,   84,   84,   84,  258,   84,   84,  187,
       84,   84,   84,   84,   84,  188,   84,   84,   84,   84,
      190,   84,   84,   84,   84,   84,  189,   84,  193,  258,
       84,   84,  191,   84,  194,   84,   84,   84,  258,  258,
      258,   84,  258,   84,  258,  258,   84,   84,   84,   84,
      258,  258,   84,   84,   84,  258,   84,  258,  258,   84,
       84,   84,   84,   84,  258,   84,   84,  258,  195,   84,
       84,   84,   84,   84,   84,   84,   84,  258,   84,  258,
      258,   84,   84,   84,   84,  258,  258,   84,   84,   84,

      258,   84,  258,  258,   84,   84,  196,   84,   84,  258,
      197,   84,  198,   84,  258,  258,   84,  258,   84,   84,
       84,   84,  258,   84,   84,   84,   84,  199,   84,   84,
       84,   84,  258,   84,   84,   84,   84,  200,  258,  201,
       84,   84,  258,   84,   84,   84,  258,  203,  258,   84,
      202,   84,  258,  258,   84,   84,  204,   84,  258,  258,
       84,   84,   84,  258,  205,  258,  258,   84,  258,  258,
       84,  258,   84,   84,   84,   84,  258,   84,   84,   84,
       84,  206,   84,   84,   84,   84,  258,   84,   84,   84,
       84,  258,   84,   84,   84,   84,  258,   84,   84,   84,

       84,  207,   84,   84,   84,   84,  208,  209,   84,   84,
       84,  210,   84,   84,   84,   84,  258,  258,   84,   84,
       84,   84,  258,   84,   84,  258,  258,  258,  258,  211,
      258,   84,   84,   84,  212,  213,   84,  258,   84,   84,
      258,  258,   84,   84,   84,   84,   84,   84,   84,   84,
       84,  258,   84,   84,  214,  215,   84,   84,   84,  258,
       84,  221,  258,   84,   84,   84,   84,  216,  258,   84,
       84,   84,  258,  217,  258,  218,   84,   84,  219,   84,
       84,  258,   84,   84,  258,   84,   84,  220,   84,   84,
       84,   84,   84,   84,   84,  258,   84,   84,  258,   84,

      258,   84,   84,  258,  258,   84,   84,   84,  258,   84,
      222,   84,   84,   84,   84,  258,  223,  224,  258,   84,
      258,   84,   84,  258,  258,   84,   84,   84,  226,  227,
      225,   84,   84,   84,   84,  258,   84,  228,  258,  258,
      258,  258,   84,  258,   84,   84,   84,   84,   84,  229,
      230,   84,  258,   84,  258,  231,  258,  258,   84,   84,
       84,  232,   84,   84,   84,   84,   84,  258,   84,   84,
       84,   84,   84,   84,  258,  233,  258,  258,   84,  258,
       84,   84,  258,  258,   84,   84,   84,   84,   84,   84,
       84,   84,   84,  234,   84,   84,   84,  258,   84,   84,

      258,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,  258,   84,  258,
      236,   84,   84,   84,   84,  238,  235,   84,   84,  258,
      258,   84,   84,   84,   84,   84,   84,   84,  237,  258,
       84,   84,  258,   84,   84,  240,  258,  258,   84,   84,
      241,  258,   84,   84,  239,   84,   84,   84,  258,   84,
       84,  258,  258,   84,   84,   84,   84,  242,   84,   84,
       84,  258,   84,  258,  243,   84,   84,  244,   84,   84,
      258,   84,   84,  245,   84,   84,  258,   84,   84,   84,
       84,   84,  246,   84,  258,   84,   84,  247,  258,   84,

      258,   84,  248,  258,   84,   84,   84,   84,   84,  258,
       84,   84,  258,   84,   84,  258,   84,   84,   84,  249,
       84,   84,  258,   84,   84,   84,  250,  258,   84,  258,
      258,   84,  258,   84,   84,   84,   84,  258,  251,   84,
       84,   84,  252,   84,   84,   84,  258,  258,   84,  258,
       84,   84,  258,  258,   84,   84,   84,  253,   84,   84,
       84,   84,   84,   84,  258,   84,  258,  258,  258,  258,
      258,   84,   84,   84,   84,   84,   84,   84,  254,   84,
       84,   84,  258,   84,   84,  258,  258,   84,   84,   84,
       84,  255,   84,   84,   84,  258,   84,  256,  258,   84,

       84,   84,   84,  258,  258,   84,   84,  258,  258,   84,
      258,  258,   84,   84,  258,  257,   65,   65,   65,   65,
       66,   66,   66,   66,   84,   84,  121,  258,  121,  121,
       15,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258

    } ;

static const flex_int16_t yy_chk[1396] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   13,   14,   20,   29,   30,   30,
       13,   14,   29,   33,   34,   34,   36,  261,   33,   37,
       38,   75,   75,   39,   36,  161,   70,   37,   38,   36,
       20,   39,   37,   38,   36,   48,   39,   37,   38,   48,

       77,   39,   68,   48,   64,   40,   48,   48,   36,   41,
       70,   37,   38,   40,   62,   39,   39,   41,   40,   33,
       44,   38,   41,   40,   37,   71,   45,   41,   44,   35,
       31,   27,   19,   44,   45,   15,    0,   40,   44,   45,
        0,   41,    0,   46,   45,    0,    0,   47,    0,   71,
       40,   46,   44,   41,    0,   47,   46,    0,   45,   45,
       47,   46,   49,    0,   44,   47,    0,   49,   44,    0,
       49,   45,    0,   49,   49,   46,    0,    0,   50,   47,
       47,    0,   50,    0,    0,   46,   50,   51,   47,   50,
       50,   47,   47,   52,    0,   51,   46,   52,   51,   51,

       53,   52,    0,    0,   52,   52,    0,   54,   53,   55,
        0,   53,   53,   55,   53,   54,   56,   55,   54,   54,
       55,   55,    0,   57,   56,    0,    0,   56,   56,    0,
       57,   57,    0,   56,   57,   57,    0,   57,   58,    0,
       59,    0,    0,    0,   57,   60,   58,   83,   59,   58,
       58,   59,   59,   60,   84,   83,   60,   60,   83,   83,
       85,    0,   84,    0,    0,   84,   84,   86,   85,   87,
        0,   85,   85,    0,    0,   86,   85,   87,   86,   86,
       87,   87,   86,   88,    0,   87,    0,    0,    0,   89,
        0,   88,    0,    0,   88,   88,   88,   89,    0,   90,

       89,   89,   90,    0,   91,    0,   92,   90,    0,    0,
       90,   90,   91,    0,   92,   91,   91,   92,   92,   93,
        0,   92,   92,    0,   94,    0,   95,   93,   95,    0,
       93,   93,   94,   93,   95,   94,   94,   95,   95,   94,
       96,    0,   95,    0,    0,   97,    0,   98,   96,   96,
        0,   96,   96,   97,    0,   98,   97,   97,   98,   98,
       99,    0,    0,    0,    0,   97,    0,  100,   99,   99,
        0,   99,   99,  101,   99,  100,    0,    0,  100,  100,
      102,  101,    0,    0,  101,  101,    0,  103,  102,  102,
        0,  102,  102,  104,  102,  103,    0,    0,  103,  103,

      105,  104,  106,    0,  104,  104,    0,  107,  105,  104,
      106,  105,  105,  106,  106,  107,  105,  108,  107,  107,
        0,  106,  109,  107,  110,  108,    0,    0,  108,  108,
      109,    0,  110,  109,  109,  110,  110,  111,    0,  111,
      110,    0,  112,    0,    0,  111,  112,  113,  111,  111,
      112,    0,    0,  112,  112,  113,  112,    0,  113,  113,
        0,  114,    0,    0,  113,    0,    0,    0,  113,  114,
      115,    0,  114,  114,  114,  115,  116,    0,  115,    0,
        0,  115,  115,  117,  116,  124,    0,  116,  116,    0,
      116,  117,    0,  124,  117,  117,  124,  124,    0,  117,

      122,  122,    0,    0,    0,    0,  123,    0,  122,  122,
      122,  122,  122,  122,  123,  123,    0,  123,  123,  126,
      125,    0,  122,  122,  122,  122,  122,  122,  125,  127,
        0,  125,  125,    0,  129,    0,  125,  127,    0,  126,
      127,  127,  129,    0,  128,  129,  129,  126,    0,    0,
      126,  126,  128,  130,    0,  128,  128,    0,    0,    0,
      128,  130,    0,    0,  130,  130,  131,    0,  131,  130,
        0,  132,    0,    0,  131,    0,  133,  131,  131,  132,
      133,  134,  132,  132,  133,  134,  132,  133,  133,  134,
      135,    0,  134,  134,  135,  136,    0,  137,  135,  136,

        0,  135,  135,  136,    0,  137,  136,  136,  137,  137,
      138,    0,  137,    0,    0,    0,  139,    0,  138,  139,
        0,  138,  138,  140,  139,  141,    0,  139,  139,  141,
      142,  140,  143,  141,  140,  140,  141,  141,  142,  144,
      143,  142,  142,  143,  143,  144,  145,  144,    0,    0,
      144,  144,    0,  146,  145,  146,    0,  145,  145,  147,
      145,  146,    0,    0,  146,  146,  148,  147,  149,    0,
      147,  147,    0,  150,  148,    0,  149,  148,  148,  149,
      149,  150,    0,    0,  150,  150,  151,    0,  151,    0,
      150,  152,    0,  153,  151,    0,    0,  151,  151,  152,

      155,  153,  152,  152,  153,  153,  154,    0,  155,    0,
      154,  155,  155,  157,  154,  156,    0,  154,  154,  156,
      158,  157,  159,  156,  157,  157,  156,  156,  158,  162,
      159,  158,  158,  159,  159,  160,  158,  162,  163,    0,
      162,  162,  160,  160,  164,  165,  160,  160,    0,    0,
        0,  166,    0,  165,    0,    0,  165,  165,  163,  166,
        0,    0,  166,  166,  164,    0,  163,    0,    0,  163,
      163,  167,  164,  168,    0,  164,  164,    0,  167,  167,
      169,  168,  167,  167,  168,  168,  170,    0,  169,    0,
        0,  169,  169,  171,  170,    0,    0,  170,  170,  172,

        0,  171,    0,    0,  171,  171,  171,  172,  173,    0,
      172,  172,  173,  174,    0,    0,  173,    0,  175,  173,
      173,  174,    0,  176,  174,  174,  175,  175,  177,  175,
      175,  176,    0,  178,  176,  176,  177,  176,    0,  177,
      177,  178,    0,  179,  178,  178,    0,  179,    0,  180,
      178,  179,    0,    0,  179,  179,  180,  180,    0,    0,
      180,  180,  181,    0,  181,    0,    0,  182,    0,    0,
      181,    0,  183,  181,  181,  182,    0,  184,  182,  182,
      183,  182,  185,  183,  183,  184,    0,  186,  184,  184,
      185,    0,  187,  185,  185,  186,    0,  188,  186,  186,

      187,  185,  189,  187,  187,  188,  188,  190,  188,  188,
      189,  193,  191,  189,  189,  190,    0,    0,  190,  190,
      191,  194,    0,  191,  191,    0,    0,    0,    0,  194,
        0,  193,  194,  194,  194,  194,  195,    0,  196,  193,
        0,    0,  193,  193,  195,  198,  196,  195,  195,  196,
      196,    0,  197,  198,  196,  197,  198,  198,  199,    0,
      197,  205,    0,  197,  197,  200,  199,  199,    0,  199,
      199,  201,    0,  200,    0,  201,  200,  200,  202,  201,
      204,    0,  201,  201,    0,  203,  202,  203,  204,  202,
      202,  204,  204,  203,  205,    0,  203,  203,    0,  206,

        0,  207,  205,    0,    0,  205,  205,  206,    0,  207,
      206,  206,  207,  207,  208,    0,  207,  208,    0,  209,
        0,  210,  208,    0,    0,  208,  208,  209,  210,  210,
      209,  209,  210,  210,  211,    0,  212,  210,    0,    0,
        0,    0,  211,    0,  212,  211,  211,  212,  212,  211,
      212,  213,    0,  214,    0,  213,    0,    0,  215,  213,
      216,  214,  213,  213,  214,  214,  215,    0,  216,  215,
      215,  216,  216,  217,    0,  217,    0,    0,  218,    0,
      220,  217,    0,    0,  217,  217,  218,  219,  220,  218,
      218,  220,  220,  219,  221,  219,  222,    0,  219,  219,

        0,  223,  221,  224,  222,  221,  221,  222,  222,  223,
      225,  224,  223,  223,  224,  224,  226,    0,  225,    0,
      226,  225,  225,  227,  226,  228,  225,  226,  226,    0,
        0,  227,  229,  228,  227,  227,  228,  228,  227,    0,
      229,  230,    0,  229,  229,  230,    0,    0,  231,  230,
      231,    0,  230,  230,  229,  232,  231,  233,    0,  231,
      231,    0,    0,  232,  235,  233,  232,  232,  233,  233,
      234,    0,  235,    0,  234,  235,  235,  236,  234,  237,
        0,  234,  234,  237,  238,  236,    0,  237,  236,  236,
      237,  237,  238,  239,    0,  238,  238,  239,    0,  240,

        0,  239,  240,    0,  239,  239,  241,  240,  242,    0,
      240,  240,    0,  243,  241,    0,  242,  241,  241,  242,
      242,  243,    0,  244,  243,  243,  244,    0,  245,    0,
        0,  244,    0,  246,  244,  244,  245,    0,  245,  245,
      245,  246,  246,  247,  246,  246,    0,    0,  248,    0,
      249,  247,    0,    0,  247,  247,  248,  247,  249,  248,
      248,  249,  249,  250,    0,  251,    0,    0,    0,    0,
        0,  250,  252,  251,  250,  250,  251,  251,  251,  253,
      252,  254,    0,  252,  252,    0,    0,  253,  255,  254,
      253,  253,  254,  254,  256,    0,  255,  254,    0,  255,

      255,  257,  256,    0,    0,  256,  256,    0,    0,  257,
        0,    0,  257,  257,    0,  256,  259,  259,  259,  259,
      260,  260,  260,  260,  262,  262,  263,    0,  263,  263,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "Stella.l"
/* -*- c++ -*- File generated by the BNF Converter (bnfc 2.9.4.1). */
/* Lexer definition for use with FLex */
#define YY_NO_INPUT 1
#line 10 "Stella.l"
#include "Absyn.H"
#include "Bison.H"

#define initialize_lexer Stella_initialize_lexer

static void update_loc(YYLTYPE* loc, char* text)
{
  loc->first_line = loc->last_line;
  loc->first_column = loc->last_column;
  int i = 0;
  for (; text[i] != '\0'; ++i) {
      if (text[i] == '\n') {
          ++loc->last_line;
          loc->last_column = 0;
      } else {
          ++loc->last_column;
      }
  }
}
#define YY_USER_ACTION update_loc(yylloc, yytext);

#line 1076 "Lexer.C"

#line 1078 "Lexer.C"

#define INITIAL 0
#define CHAR 1
#define CHARESC 2
#define CHAREND 3
#define STRING 4
#define ESCAPED 5
#define COMMENT 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			yy_size_t yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 40 "Stella.l"


#line 1369 "Lexer.C"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 259 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1331 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "Stella.l"
return _COMMA;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "Stella.l"
return _SEMI;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 44 "Stella.l"
return _LPAREN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "Stella.l"
return _RPAREN;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "Stella.l"
return _LBRACE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "Stella.l"
return _RBRACE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "Stella.l"
return _LBRACK;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "Stella.l"
return _RBRACK;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "Stella.l"
return _EQ;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "Stella.l"
return _COLON;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "Stella.l"
return _RARROW;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "Stella.l"
return _RDARROW;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "Stella.l"
return _BAR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "Stella.l"
return _SYMB_13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "Stella.l"
return _SYMB_14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "Stella.l"
return _COLONEQ;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "Stella.l"
return _LT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "Stella.l"
return _LDARROW;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "Stella.l"
return _GT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "Stella.l"
return _GTEQ;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "Stella.l"
return _DEQ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "Stella.l"
return _BANGEQ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "Stella.l"
return _PLUS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "Stella.l"
return _MINUS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "Stella.l"
return _STAR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "Stella.l"
return _SLASH;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "Stella.l"
return _DOT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "Stella.l"
return _SYMB_27;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "Stella.l"
return _SYMB_28;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "Stella.l"
return _SYMB_29;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "Stella.l"
return _SYMB_30;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "Stella.l"
return _SYMB_31;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "Stella.l"
return _SYMB_32;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "Stella.l"
return _SYMB_33;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "Stella.l"
return _AMP;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "Stella.l"
return _KW_Bool;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "Stella.l"
return _KW_Bot;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "Stella.l"
return _KW_Nat;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "Stella.l"
return _KW_Top;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "Stella.l"
return _KW_Unit;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 82 "Stella.l"
return _KW_and;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 83 "Stella.l"
return _KW_as;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "Stella.l"
return _KW_cast;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 85 "Stella.l"
return _KW_catch;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 86 "Stella.l"
return _KW_cons;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "Stella.l"
return _KW_core;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "Stella.l"
return _KW_else;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "Stella.l"
return _KW_exception;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "Stella.l"
return _KW_extend;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "Stella.l"
return _KW_false;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "Stella.l"
return _KW_fix;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "Stella.l"
return _KW_fn;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "Stella.l"
return _KW_fold;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "Stella.l"
return _KW_forall;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "Stella.l"
return _KW_generic;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "Stella.l"
return _KW_if;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "Stella.l"
return _KW_in;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "Stella.l"
return _KW_inl;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "Stella.l"
return _KW_inline;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "Stella.l"
return _KW_inr;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "Stella.l"
return _KW_language;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "Stella.l"
return _KW_let;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "Stella.l"
return _KW_letrec;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "Stella.l"
return _KW_match;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "Stella.l"
return _KW_new;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "Stella.l"
return _KW_not;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "Stella.l"
return _KW_or;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "Stella.l"
return _KW_return;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "Stella.l"
return _KW_succ;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "Stella.l"
return _KW_then;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "Stella.l"
return _KW_throw;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "Stella.l"
return _KW_throws;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "Stella.l"
return _KW_true;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "Stella.l"
return _KW_try;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 "Stella.l"
return _KW_type;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "Stella.l"
return _KW_unfold;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "Stella.l"
return _KW_unit;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "Stella.l"
return _KW_variant;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 120 "Stella.l"
return _KW_with;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 121 "Stella.l"
return _KW_79;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 123 "Stella.l"
/* skip */; /* BNFC: comment "//" */
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 124 "Stella.l"
BEGIN COMMENT;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 125 "Stella.l"
BEGIN INITIAL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 126 "Stella.l"
/* skip */;
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 127 "Stella.l"
/* skip */;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "Stella.l"
yylval->_string = strdup(yytext); return T_StellaIdent;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "Stella.l"
yylval->_string = strdup(yytext); return T_ExtensionName;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "Stella.l"
yylval->_string = strdup(yytext); return T_MemoryAddress;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "Stella.l"
yylval->_int = atoi(yytext); return _INTEGER_;
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 133 "Stella.l"
/* ignore white space. */;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 134 "Stella.l"
return _ERROR_;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 136 "Stella.l"
ECHO;
	YY_BREAK
#line 1888 "Lexer.C"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(CHARESC):
case YY_STATE_EOF(CHAREND):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(ESCAPED):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 259 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 259 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 258);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 136 "Stella.l"


yyscan_t initialize_lexer(FILE *inp)
{
  yyscan_t scanner;
  if (yylex_init_extra(NULL, &scanner)) return 0;
  if (inp) yyrestart(inp, scanner);
  return scanner;
}


